logging:
  level:
    root: info
    br.com: trace

server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/crudtest
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  flyway:
    locations: classpath:/db/migration
    #schemas: public
    baseline-on-migrate: true
    #baseline-version: 2
    ignore-missing-migrations: false
    ignore-ignored-migrations: false
    out-of-order: false
