#https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core
logging:
  level:
    root: info
    br.com: trace

server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
