CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  document VARCHAR(255),
  customer_type VARCHAR(255),
  firstname VARCHAR(255),
  lastname VARCHAR(255),
  birthdate date,
  country VARCHAR(255),
  email VARCHAR(255),
  phone_number VARCHAR(255),
  job_title VARCHAR(255),
  company VARCHAR(255),
  date_created TIMESTAMP,
  last_updated TIMESTAMP,
  CONSTRAINT pk_customer PRIMARY KEY (id)
);